spring:
    profiles:
        active: local
    application:
        name: skydatageo
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: test
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                show_sql: true
                format_sql: true
        show-sql: true

logging:
    level:
        org.hibernate.SQL: DEBUG
        org.hibernate.tool.schema: DEBUG
        org.hibernate.spatial: DEBUG